# example netlify.toml
[build]
  command = "next build"
  publish = ".next"

[functions]
  node_bundler = "esbuild"
  external_node_modules = [ "@ampproject/toolbox-optimizer", "sharp"]

[[plugins]]
  package = "@netlify/plugin-nextjs"
